[package]
name = "play-rust-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
duckdb = "^1"
rocket = { version = ">=0.5.0, <1", features = ["json"] }
serde = { version = "^1", features = ["derive"] }
